# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Srikar Sarma PV
title: Software Development Engineer
email: srikarsarma@gmail.com
website: www.github.com/srikarpv/srikar.github.io

# Social links
twitter_username: iamsrikar
github_username:  srikarpv
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: iamsrikar
linkedin_username: srikarpv
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My Name is SRIKAR, I am a graduate student at the University of Central Florida. My interests lie in the areas of Machine Learning, Natural Language Processing, Computer Vision and Algorithms. I’m working as a Graduate Research Assistant in the CASS (High Performance Computing ) Lab at UCF under the guidance of Dr. JUN WANG, Dr. Sumith Jha. I received my bachelor's degree (B.E) in Computer Science from Visvesvaraya Technological University, Bangalore, India.

  I am most skilled in: <mark>Python, Java, C++</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in  software engineering some of my other interests and hobbies are:
   - Basketball
   - Hiking
   - Running
   - music production

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
